logging:
  config: classpath:config/logback-dev.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
  # Redis
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    pool:
      max-active: 20
  dubbo:
      application:
        name: demo-provider
      scan: com.example.demo
      protocol:
        name: dubbo
        port: -1
      registry:
        address: zookeeper://127.0.0.1:2181
# Dubbo
#dubbo:
#  application:
#    id: demo-provider
#    name: demo-provider
#  consumer:
#    check: false
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: -1
#  registry:
#    id: my-registry
#    address: zookeeper://127.0.0.1:2181