server:
  port: 8089
logging:
  config: classpath:config/logback-dev.xml
spring:
  # Redis
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
    pool:
      max-active: 20
  boot:
    swagger2:
      allow: true
      base-package: com.example.demo
      title: DEMO-MANAGER
      description: springboot api docs for swagger2
      service-url: http://127.0.0.1:8089
      contact:
      version: 1.0.0
      host: 127.0.0.1:8089
  #Dubbo
  dubbo:
    application:
      name: demo-consumer
    scan: com.example.demo
    protocol:
      name: dubbo
      port: -1
    registry:
      address: zookeeper://127.0.0.1:2181

